//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.22 at 03:38:06 PM EEST 
//


package ehi.web.service.client.soap.schemas.gps;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="Acquirer_id_DE32" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ActBal" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="Additional_Amt_DE54" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Amt_Tran_Fee_DE28" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Auth_Code_DE38" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Avl_Bal" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="Bill_Amt" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="Bill_Ccy" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="BlkAmt" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="Cust_Ref" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="FX_Pad" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="Fee_Fixed" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="Fee_Rate" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="LoadSRC" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="LoadType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="MCC_Code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="MCC_Desc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="MCC_Pad" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="Merch_ID_DE42" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Merch_Name_DE43" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Note" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="POS_Data_DE22" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="POS_Data_DE61" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="POS_Termnl_DE41" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="POS_Time_DE12" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Proc_Code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Resp_Code_DE39" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Ret_Ref_No_DE37" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Settle_Amt" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="Settle_Ccy" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Status_Code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Token" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Trans_link" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Txn_Amt" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="Txn_CCy" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Txn_Ctry" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Txn_Desc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Txn_GPS_Date" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="TXn_ID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Txn_Stat_Code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="TXN_Time_DE07" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Txn_Type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Additional_Data_DE48" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Authorised_by_GPS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="AVS_Result" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CU_Group" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="InstCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="MTID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ProductID" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="Record_Data_DE120" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SubBIN" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="TLogIDOrg" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="VL_Group" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Dom_Fee_Fixed" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Non_Dom_Fee_Fixed" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Fx_Fee_Fixed" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Other_Fee_Amt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Fx_Fee_Rate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Dom_Fee_Rate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Non_Dom_Fee_Rate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Additional_Data_DE124" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CVV2" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Expiry_Date" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PAN_Sequence_Number" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PIN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PIN_Enc_Algorithm" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PIN_Format" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PIN_Key_Index" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SendingAttemptCount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="source_bank_ctry" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="source_bank_account_format" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="source_bank_account" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="dest_bank_ctry" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="dest_bank_account_format" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="dest_bank_account" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="GPS_POS_Capability" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="GPS_POS_Data" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Acquirer_Reference_Data_031" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Response_Source" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Response_Source_Why" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Message_Source" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Message_Why" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="traceid_lifecycle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Balance_Sequence" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="Balance_Sequence_Exthost" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="PaymentToken_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PaymentToken_creator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PaymentToken_expdate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PaymentToken_type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PaymentToken_status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PaymentToken_creatorStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PaymentToken_wallet" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PaymentToken_deviceType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PaymentToken_lang" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PaymentToken_deviceTelNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PaymentToken_deviceIp" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PaymentToken_deviceId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PaymentToken_deviceName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PaymentToken_activationCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PaymentToken_activationExpiry" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PaymentToken_activationMethod" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PaymentToken_activationMethodData" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ICC_System_Related_Data_DE55" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Merch_Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Merch_Street" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Merch_City" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Merch_Region" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Merch_Postcode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Merch_Country" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Merch_Tel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Merch_URL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Merch_Name_Other" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Merch_Net_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Merch_Tax_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Merch_Contact" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "GetTransaction")
public class GetTransaction {

    @XmlElement(name = "Acquirer_id_DE32")
    protected String acquirerIdDE32;
    @XmlElement(name = "ActBal")
    protected double actBal;
    @XmlElement(name = "Additional_Amt_DE54")
    protected String additionalAmtDE54;
    @XmlElement(name = "Amt_Tran_Fee_DE28")
    protected String amtTranFeeDE28;
    @XmlElement(name = "Auth_Code_DE38")
    protected String authCodeDE38;
    @XmlElement(name = "Avl_Bal")
    protected double avlBal;
    @XmlElement(name = "Bill_Amt")
    protected double billAmt;
    @XmlElement(name = "Bill_Ccy")
    protected String billCcy;
    @XmlElement(name = "BlkAmt")
    protected double blkAmt;
    @XmlElement(name = "Cust_Ref")
    protected String custRef;
    @XmlElement(name = "FX_Pad")
    protected Double fxPad;
    @XmlElement(name = "Fee_Fixed")
    protected double feeFixed;
    @XmlElement(name = "Fee_Rate")
    protected double feeRate;
    @XmlElement(name = "LoadSRC")
    protected String loadSRC;
    @XmlElement(name = "LoadType")
    protected String loadType;
    @XmlElement(name = "MCC_Code")
    protected String mccCode;
    @XmlElement(name = "MCC_Desc")
    protected String mccDesc;
    @XmlElement(name = "MCC_Pad")
    protected double mccPad;
    @XmlElement(name = "Merch_ID_DE42")
    protected String merchIDDE42;
    @XmlElement(name = "Merch_Name_DE43")
    protected String merchNameDE43;
    @XmlElement(name = "Note")
    protected String note;
    @XmlElement(name = "POS_Data_DE22")
    protected String posDataDE22;
    @XmlElement(name = "POS_Data_DE61")
    protected String posDataDE61;
    @XmlElement(name = "POS_Termnl_DE41")
    protected String posTermnlDE41;
    @XmlElement(name = "POS_Time_DE12")
    protected String posTimeDE12;
    @XmlElement(name = "Proc_Code")
    protected String procCode;
    @XmlElement(name = "Resp_Code_DE39")
    protected String respCodeDE39;
    @XmlElement(name = "Ret_Ref_No_DE37")
    protected String retRefNoDE37;
    @XmlElement(name = "Settle_Amt")
    protected double settleAmt;
    @XmlElement(name = "Settle_Ccy")
    protected String settleCcy;
    @XmlElement(name = "Status_Code")
    protected String statusCode;
    @XmlElement(name = "Token")
    protected String token;
    @XmlElement(name = "Trans_link")
    protected String transLink;
    @XmlElement(name = "Txn_Amt")
    protected double txnAmt;
    @XmlElement(name = "Txn_CCy")
    protected String txnCCy;
    @XmlElement(name = "Txn_Ctry")
    protected String txnCtry;
    @XmlElement(name = "Txn_Desc")
    protected String txnDesc;
    @XmlElement(name = "Txn_GPS_Date")
    protected String txnGPSDate;
    @XmlElement(name = "TXn_ID", required = true)
    protected String tXnID;
    @XmlElement(name = "Txn_Stat_Code")
    protected String txnStatCode;
    @XmlElement(name = "TXN_Time_DE07")
    protected String txnTimeDE07;
    @XmlElement(name = "Txn_Type")
    protected String txnType;
    @XmlElement(name = "Additional_Data_DE48")
    protected String additionalDataDE48;
    @XmlElement(name = "Authorised_by_GPS")
    protected String authorisedByGPS;
    @XmlElement(name = "AVS_Result")
    protected String avsResult;
    @XmlElement(name = "CU_Group")
    protected String cuGroup;
    @XmlElement(name = "InstCode")
    protected String instCode;
    @XmlElement(name = "MTID")
    protected String mtid;
    @XmlElement(name = "ProductID")
    protected int productID;
    @XmlElement(name = "Record_Data_DE120")
    protected String recordDataDE120;
    @XmlElement(name = "SubBIN")
    protected int subBIN;
    @XmlElement(name = "TLogIDOrg")
    protected String tLogIDOrg;
    @XmlElement(name = "VL_Group")
    protected String vlGroup;
    @XmlElement(name = "Dom_Fee_Fixed")
    protected String domFeeFixed;
    @XmlElement(name = "Non_Dom_Fee_Fixed")
    protected String nonDomFeeFixed;
    @XmlElement(name = "Fx_Fee_Fixed")
    protected String fxFeeFixed;
    @XmlElement(name = "Other_Fee_Amt")
    protected String otherFeeAmt;
    @XmlElement(name = "Fx_Fee_Rate")
    protected String fxFeeRate;
    @XmlElement(name = "Dom_Fee_Rate")
    protected String domFeeRate;
    @XmlElement(name = "Non_Dom_Fee_Rate")
    protected String nonDomFeeRate;
    @XmlElement(name = "Additional_Data_DE124")
    protected String additionalDataDE124;
    @XmlElement(name = "CVV2", required = true)
    protected String cvv2;
    @XmlElement(name = "Expiry_Date")
    protected String expiryDate;
    @XmlElement(name = "PAN_Sequence_Number")
    protected String panSequenceNumber;
    @XmlElement(name = "PIN")
    protected String pin;
    @XmlElement(name = "PIN_Enc_Algorithm")
    protected String pinEncAlgorithm;
    @XmlElement(name = "PIN_Format")
    protected String pinFormat;
    @XmlElement(name = "PIN_Key_Index")
    protected String pinKeyIndex;
    @XmlElement(name = "SendingAttemptCount")
    protected String sendingAttemptCount;
    @XmlElement(name = "source_bank_ctry")
    protected String sourceBankCtry;
    @XmlElement(name = "source_bank_account_format")
    protected String sourceBankAccountFormat;
    @XmlElement(name = "source_bank_account")
    protected String sourceBankAccount;
    @XmlElement(name = "dest_bank_ctry")
    protected String destBankCtry;
    @XmlElement(name = "dest_bank_account_format")
    protected String destBankAccountFormat;
    @XmlElement(name = "dest_bank_account")
    protected String destBankAccount;
    @XmlElement(name = "GPS_POS_Capability")
    protected String gpsposCapability;
    @XmlElement(name = "GPS_POS_Data")
    protected String gpsposData;
    @XmlElement(name = "Acquirer_Reference_Data_031")
    protected String acquirerReferenceData031;
    @XmlElement(name = "Response_Source")
    protected String responseSource;
    @XmlElement(name = "Response_Source_Why")
    protected String responseSourceWhy;
    @XmlElement(name = "Message_Source")
    protected String messageSource;
    @XmlElement(name = "Message_Why")
    protected String messageWhy;
    @XmlElement(name = "traceid_lifecycle")
    protected String traceidLifecycle;
    @XmlElement(name = "Balance_Sequence")
    protected int balanceSequence;
    @XmlElement(name = "Balance_Sequence_Exthost")
    protected int balanceSequenceExthost;
    @XmlElement(name = "PaymentToken_id")
    protected String paymentTokenId;
    @XmlElement(name = "PaymentToken_creator")
    protected String paymentTokenCreator;
    @XmlElement(name = "PaymentToken_expdate")
    protected String paymentTokenExpdate;
    @XmlElement(name = "PaymentToken_type")
    protected String paymentTokenType;
    @XmlElement(name = "PaymentToken_status")
    protected String paymentTokenStatus;
    @XmlElement(name = "PaymentToken_creatorStatus")
    protected String paymentTokenCreatorStatus;
    @XmlElement(name = "PaymentToken_wallet")
    protected String paymentTokenWallet;
    @XmlElement(name = "PaymentToken_deviceType")
    protected String paymentTokenDeviceType;
    @XmlElement(name = "PaymentToken_lang")
    protected String paymentTokenLang;
    @XmlElement(name = "PaymentToken_deviceTelNum")
    protected String paymentTokenDeviceTelNum;
    @XmlElement(name = "PaymentToken_deviceIp")
    protected String paymentTokenDeviceIp;
    @XmlElement(name = "PaymentToken_deviceId")
    protected String paymentTokenDeviceId;
    @XmlElement(name = "PaymentToken_deviceName")
    protected String paymentTokenDeviceName;
    @XmlElement(name = "PaymentToken_activationCode")
    protected String paymentTokenActivationCode;
    @XmlElement(name = "PaymentToken_activationExpiry")
    protected String paymentTokenActivationExpiry;
    @XmlElement(name = "PaymentToken_activationMethod")
    protected String paymentTokenActivationMethod;
    @XmlElement(name = "PaymentToken_activationMethodData")
    protected String paymentTokenActivationMethodData;
    @XmlElement(name = "ICC_System_Related_Data_DE55")
    protected String iccSystemRelatedDataDE55;
    @XmlElement(name = "Merch_Name")
    protected String merchName;
    @XmlElement(name = "Merch_Street")
    protected String merchStreet;
    @XmlElement(name = "Merch_City")
    protected String merchCity;
    @XmlElement(name = "Merch_Region")
    protected String merchRegion;
    @XmlElement(name = "Merch_Postcode")
    protected String merchPostcode;
    @XmlElement(name = "Merch_Country")
    protected String merchCountry;
    @XmlElement(name = "Merch_Tel")
    protected String merchTel;
    @XmlElement(name = "Merch_URL")
    protected String merchURL;
    @XmlElement(name = "Merch_Name_Other")
    protected String merchNameOther;
    @XmlElement(name = "Merch_Net_id")
    protected String merchNetId;
    @XmlElement(name = "Merch_Tax_id")
    protected String merchTaxId;
    @XmlElement(name = "Merch_Contact")
    protected String merchContact;

    /**
     * Gets the value of the acquirerIdDE32 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcquirerIdDE32() {
        return acquirerIdDE32;
    }

    /**
     * Sets the value of the acquirerIdDE32 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcquirerIdDE32(String value) {
        this.acquirerIdDE32 = value;
    }

    /**
     * Gets the value of the actBal property.
     * 
     */
    public double getActBal() {
        return actBal;
    }

    /**
     * Sets the value of the actBal property.
     * 
     */
    public void setActBal(double value) {
        this.actBal = value;
    }

    /**
     * Gets the value of the additionalAmtDE54 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdditionalAmtDE54() {
        return additionalAmtDE54;
    }

    /**
     * Sets the value of the additionalAmtDE54 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdditionalAmtDE54(String value) {
        this.additionalAmtDE54 = value;
    }

    /**
     * Gets the value of the amtTranFeeDE28 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAmtTranFeeDE28() {
        return amtTranFeeDE28;
    }

    /**
     * Sets the value of the amtTranFeeDE28 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAmtTranFeeDE28(String value) {
        this.amtTranFeeDE28 = value;
    }

    /**
     * Gets the value of the authCodeDE38 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthCodeDE38() {
        return authCodeDE38;
    }

    /**
     * Sets the value of the authCodeDE38 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthCodeDE38(String value) {
        this.authCodeDE38 = value;
    }

    /**
     * Gets the value of the avlBal property.
     * 
     */
    public double getAvlBal() {
        return avlBal;
    }

    /**
     * Sets the value of the avlBal property.
     * 
     */
    public void setAvlBal(double value) {
        this.avlBal = value;
    }

    /**
     * Gets the value of the billAmt property.
     * 
     */
    public double getBillAmt() {
        return billAmt;
    }

    /**
     * Sets the value of the billAmt property.
     * 
     */
    public void setBillAmt(double value) {
        this.billAmt = value;
    }

    /**
     * Gets the value of the billCcy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillCcy() {
        return billCcy;
    }

    /**
     * Sets the value of the billCcy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillCcy(String value) {
        this.billCcy = value;
    }

    /**
     * Gets the value of the blkAmt property.
     * 
     */
    public double getBlkAmt() {
        return blkAmt;
    }

    /**
     * Sets the value of the blkAmt property.
     * 
     */
    public void setBlkAmt(double value) {
        this.blkAmt = value;
    }

    /**
     * Gets the value of the custRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustRef() {
        return custRef;
    }

    /**
     * Sets the value of the custRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustRef(String value) {
        this.custRef = value;
    }

    /**
     * Gets the value of the fxPad property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getFXPad() {
        return fxPad;
    }

    /**
     * Sets the value of the fxPad property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setFXPad(Double value) {
        this.fxPad = value;
    }

    /**
     * Gets the value of the feeFixed property.
     * 
     */
    public double getFeeFixed() {
        return feeFixed;
    }

    /**
     * Sets the value of the feeFixed property.
     * 
     */
    public void setFeeFixed(double value) {
        this.feeFixed = value;
    }

    /**
     * Gets the value of the feeRate property.
     * 
     */
    public double getFeeRate() {
        return feeRate;
    }

    /**
     * Sets the value of the feeRate property.
     * 
     */
    public void setFeeRate(double value) {
        this.feeRate = value;
    }

    /**
     * Gets the value of the loadSRC property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoadSRC() {
        return loadSRC;
    }

    /**
     * Sets the value of the loadSRC property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoadSRC(String value) {
        this.loadSRC = value;
    }

    /**
     * Gets the value of the loadType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoadType() {
        return loadType;
    }

    /**
     * Sets the value of the loadType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoadType(String value) {
        this.loadType = value;
    }

    /**
     * Gets the value of the mccCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMCCCode() {
        return mccCode;
    }

    /**
     * Sets the value of the mccCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMCCCode(String value) {
        this.mccCode = value;
    }

    /**
     * Gets the value of the mccDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMCCDesc() {
        return mccDesc;
    }

    /**
     * Sets the value of the mccDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMCCDesc(String value) {
        this.mccDesc = value;
    }

    /**
     * Gets the value of the mccPad property.
     * 
     */
    public double getMCCPad() {
        return mccPad;
    }

    /**
     * Sets the value of the mccPad property.
     * 
     */
    public void setMCCPad(double value) {
        this.mccPad = value;
    }

    /**
     * Gets the value of the merchIDDE42 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchIDDE42() {
        return merchIDDE42;
    }

    /**
     * Sets the value of the merchIDDE42 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchIDDE42(String value) {
        this.merchIDDE42 = value;
    }

    /**
     * Gets the value of the merchNameDE43 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchNameDE43() {
        return merchNameDE43;
    }

    /**
     * Sets the value of the merchNameDE43 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchNameDE43(String value) {
        this.merchNameDE43 = value;
    }

    /**
     * Gets the value of the note property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNote() {
        return note;
    }

    /**
     * Sets the value of the note property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNote(String value) {
        this.note = value;
    }

    /**
     * Gets the value of the posDataDE22 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPOSDataDE22() {
        return posDataDE22;
    }

    /**
     * Sets the value of the posDataDE22 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPOSDataDE22(String value) {
        this.posDataDE22 = value;
    }

    /**
     * Gets the value of the posDataDE61 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPOSDataDE61() {
        return posDataDE61;
    }

    /**
     * Sets the value of the posDataDE61 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPOSDataDE61(String value) {
        this.posDataDE61 = value;
    }

    /**
     * Gets the value of the posTermnlDE41 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPOSTermnlDE41() {
        return posTermnlDE41;
    }

    /**
     * Sets the value of the posTermnlDE41 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPOSTermnlDE41(String value) {
        this.posTermnlDE41 = value;
    }

    /**
     * Gets the value of the posTimeDE12 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPOSTimeDE12() {
        return posTimeDE12;
    }

    /**
     * Sets the value of the posTimeDE12 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPOSTimeDE12(String value) {
        this.posTimeDE12 = value;
    }

    /**
     * Gets the value of the procCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcCode() {
        return procCode;
    }

    /**
     * Sets the value of the procCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcCode(String value) {
        this.procCode = value;
    }

    /**
     * Gets the value of the respCodeDE39 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRespCodeDE39() {
        return respCodeDE39;
    }

    /**
     * Sets the value of the respCodeDE39 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRespCodeDE39(String value) {
        this.respCodeDE39 = value;
    }

    /**
     * Gets the value of the retRefNoDE37 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRetRefNoDE37() {
        return retRefNoDE37;
    }

    /**
     * Sets the value of the retRefNoDE37 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRetRefNoDE37(String value) {
        this.retRefNoDE37 = value;
    }

    /**
     * Gets the value of the settleAmt property.
     * 
     */
    public double getSettleAmt() {
        return settleAmt;
    }

    /**
     * Sets the value of the settleAmt property.
     * 
     */
    public void setSettleAmt(double value) {
        this.settleAmt = value;
    }

    /**
     * Gets the value of the settleCcy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSettleCcy() {
        return settleCcy;
    }

    /**
     * Sets the value of the settleCcy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSettleCcy(String value) {
        this.settleCcy = value;
    }

    /**
     * Gets the value of the statusCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatusCode() {
        return statusCode;
    }

    /**
     * Sets the value of the statusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatusCode(String value) {
        this.statusCode = value;
    }

    /**
     * Gets the value of the token property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToken() {
        return token;
    }

    /**
     * Sets the value of the token property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToken(String value) {
        this.token = value;
    }

    /**
     * Gets the value of the transLink property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransLink() {
        return transLink;
    }

    /**
     * Sets the value of the transLink property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransLink(String value) {
        this.transLink = value;
    }

    /**
     * Gets the value of the txnAmt property.
     * 
     */
    public double getTxnAmt() {
        return txnAmt;
    }

    /**
     * Sets the value of the txnAmt property.
     * 
     */
    public void setTxnAmt(double value) {
        this.txnAmt = value;
    }

    /**
     * Gets the value of the txnCCy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTxnCCy() {
        return txnCCy;
    }

    /**
     * Sets the value of the txnCCy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTxnCCy(String value) {
        this.txnCCy = value;
    }

    /**
     * Gets the value of the txnCtry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTxnCtry() {
        return txnCtry;
    }

    /**
     * Sets the value of the txnCtry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTxnCtry(String value) {
        this.txnCtry = value;
    }

    /**
     * Gets the value of the txnDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTxnDesc() {
        return txnDesc;
    }

    /**
     * Sets the value of the txnDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTxnDesc(String value) {
        this.txnDesc = value;
    }

    /**
     * Gets the value of the txnGPSDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTxnGPSDate() {
        return txnGPSDate;
    }

    /**
     * Sets the value of the txnGPSDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTxnGPSDate(String value) {
        this.txnGPSDate = value;
    }

    /**
     * Gets the value of the tXnID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTXnID() {
        return tXnID;
    }

    /**
     * Sets the value of the tXnID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTXnID(String value) {
        this.tXnID = value;
    }

    /**
     * Gets the value of the txnStatCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTxnStatCode() {
        return txnStatCode;
    }

    /**
     * Sets the value of the txnStatCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTxnStatCode(String value) {
        this.txnStatCode = value;
    }

    /**
     * Gets the value of the txnTimeDE07 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTXNTimeDE07() {
        return txnTimeDE07;
    }

    /**
     * Sets the value of the txnTimeDE07 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTXNTimeDE07(String value) {
        this.txnTimeDE07 = value;
    }

    /**
     * Gets the value of the txnType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTxnType() {
        return txnType;
    }

    /**
     * Sets the value of the txnType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTxnType(String value) {
        this.txnType = value;
    }

    /**
     * Gets the value of the additionalDataDE48 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdditionalDataDE48() {
        return additionalDataDE48;
    }

    /**
     * Sets the value of the additionalDataDE48 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdditionalDataDE48(String value) {
        this.additionalDataDE48 = value;
    }

    /**
     * Gets the value of the authorisedByGPS property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthorisedByGPS() {
        return authorisedByGPS;
    }

    /**
     * Sets the value of the authorisedByGPS property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthorisedByGPS(String value) {
        this.authorisedByGPS = value;
    }

    /**
     * Gets the value of the avsResult property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAVSResult() {
        return avsResult;
    }

    /**
     * Sets the value of the avsResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAVSResult(String value) {
        this.avsResult = value;
    }

    /**
     * Gets the value of the cuGroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCUGroup() {
        return cuGroup;
    }

    /**
     * Sets the value of the cuGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCUGroup(String value) {
        this.cuGroup = value;
    }

    /**
     * Gets the value of the instCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstCode() {
        return instCode;
    }

    /**
     * Sets the value of the instCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstCode(String value) {
        this.instCode = value;
    }

    /**
     * Gets the value of the mtid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMTID() {
        return mtid;
    }

    /**
     * Sets the value of the mtid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMTID(String value) {
        this.mtid = value;
    }

    /**
     * Gets the value of the productID property.
     * 
     */
    public int getProductID() {
        return productID;
    }

    /**
     * Sets the value of the productID property.
     * 
     */
    public void setProductID(int value) {
        this.productID = value;
    }

    /**
     * Gets the value of the recordDataDE120 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecordDataDE120() {
        return recordDataDE120;
    }

    /**
     * Sets the value of the recordDataDE120 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecordDataDE120(String value) {
        this.recordDataDE120 = value;
    }

    /**
     * Gets the value of the subBIN property.
     * 
     */
    public int getSubBIN() {
        return subBIN;
    }

    /**
     * Sets the value of the subBIN property.
     * 
     */
    public void setSubBIN(int value) {
        this.subBIN = value;
    }

    /**
     * Gets the value of the tLogIDOrg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTLogIDOrg() {
        return tLogIDOrg;
    }

    /**
     * Sets the value of the tLogIDOrg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTLogIDOrg(String value) {
        this.tLogIDOrg = value;
    }

    /**
     * Gets the value of the vlGroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVLGroup() {
        return vlGroup;
    }

    /**
     * Sets the value of the vlGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVLGroup(String value) {
        this.vlGroup = value;
    }

    /**
     * Gets the value of the domFeeFixed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDomFeeFixed() {
        return domFeeFixed;
    }

    /**
     * Sets the value of the domFeeFixed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDomFeeFixed(String value) {
        this.domFeeFixed = value;
    }

    /**
     * Gets the value of the nonDomFeeFixed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNonDomFeeFixed() {
        return nonDomFeeFixed;
    }

    /**
     * Sets the value of the nonDomFeeFixed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNonDomFeeFixed(String value) {
        this.nonDomFeeFixed = value;
    }

    /**
     * Gets the value of the fxFeeFixed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFxFeeFixed() {
        return fxFeeFixed;
    }

    /**
     * Sets the value of the fxFeeFixed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFxFeeFixed(String value) {
        this.fxFeeFixed = value;
    }

    /**
     * Gets the value of the otherFeeAmt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtherFeeAmt() {
        return otherFeeAmt;
    }

    /**
     * Sets the value of the otherFeeAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtherFeeAmt(String value) {
        this.otherFeeAmt = value;
    }

    /**
     * Gets the value of the fxFeeRate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFxFeeRate() {
        return fxFeeRate;
    }

    /**
     * Sets the value of the fxFeeRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFxFeeRate(String value) {
        this.fxFeeRate = value;
    }

    /**
     * Gets the value of the domFeeRate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDomFeeRate() {
        return domFeeRate;
    }

    /**
     * Sets the value of the domFeeRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDomFeeRate(String value) {
        this.domFeeRate = value;
    }

    /**
     * Gets the value of the nonDomFeeRate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNonDomFeeRate() {
        return nonDomFeeRate;
    }

    /**
     * Sets the value of the nonDomFeeRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNonDomFeeRate(String value) {
        this.nonDomFeeRate = value;
    }

    /**
     * Gets the value of the additionalDataDE124 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdditionalDataDE124() {
        return additionalDataDE124;
    }

    /**
     * Sets the value of the additionalDataDE124 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdditionalDataDE124(String value) {
        this.additionalDataDE124 = value;
    }

    /**
     * Gets the value of the cvv2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCVV2() {
        return cvv2;
    }

    /**
     * Sets the value of the cvv2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCVV2(String value) {
        this.cvv2 = value;
    }

    /**
     * Gets the value of the expiryDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExpiryDate() {
        return expiryDate;
    }

    /**
     * Sets the value of the expiryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExpiryDate(String value) {
        this.expiryDate = value;
    }

    /**
     * Gets the value of the panSequenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPANSequenceNumber() {
        return panSequenceNumber;
    }

    /**
     * Sets the value of the panSequenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPANSequenceNumber(String value) {
        this.panSequenceNumber = value;
    }

    /**
     * Gets the value of the pin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPIN() {
        return pin;
    }

    /**
     * Sets the value of the pin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPIN(String value) {
        this.pin = value;
    }

    /**
     * Gets the value of the pinEncAlgorithm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPINEncAlgorithm() {
        return pinEncAlgorithm;
    }

    /**
     * Sets the value of the pinEncAlgorithm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPINEncAlgorithm(String value) {
        this.pinEncAlgorithm = value;
    }

    /**
     * Gets the value of the pinFormat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPINFormat() {
        return pinFormat;
    }

    /**
     * Sets the value of the pinFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPINFormat(String value) {
        this.pinFormat = value;
    }

    /**
     * Gets the value of the pinKeyIndex property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPINKeyIndex() {
        return pinKeyIndex;
    }

    /**
     * Sets the value of the pinKeyIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPINKeyIndex(String value) {
        this.pinKeyIndex = value;
    }

    /**
     * Gets the value of the sendingAttemptCount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSendingAttemptCount() {
        return sendingAttemptCount;
    }

    /**
     * Sets the value of the sendingAttemptCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSendingAttemptCount(String value) {
        this.sendingAttemptCount = value;
    }

    /**
     * Gets the value of the sourceBankCtry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceBankCtry() {
        return sourceBankCtry;
    }

    /**
     * Sets the value of the sourceBankCtry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceBankCtry(String value) {
        this.sourceBankCtry = value;
    }

    /**
     * Gets the value of the sourceBankAccountFormat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceBankAccountFormat() {
        return sourceBankAccountFormat;
    }

    /**
     * Sets the value of the sourceBankAccountFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceBankAccountFormat(String value) {
        this.sourceBankAccountFormat = value;
    }

    /**
     * Gets the value of the sourceBankAccount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceBankAccount() {
        return sourceBankAccount;
    }

    /**
     * Sets the value of the sourceBankAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceBankAccount(String value) {
        this.sourceBankAccount = value;
    }

    /**
     * Gets the value of the destBankCtry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestBankCtry() {
        return destBankCtry;
    }

    /**
     * Sets the value of the destBankCtry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestBankCtry(String value) {
        this.destBankCtry = value;
    }

    /**
     * Gets the value of the destBankAccountFormat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestBankAccountFormat() {
        return destBankAccountFormat;
    }

    /**
     * Sets the value of the destBankAccountFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestBankAccountFormat(String value) {
        this.destBankAccountFormat = value;
    }

    /**
     * Gets the value of the destBankAccount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestBankAccount() {
        return destBankAccount;
    }

    /**
     * Sets the value of the destBankAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestBankAccount(String value) {
        this.destBankAccount = value;
    }

    /**
     * Gets the value of the gpsposCapability property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGPSPOSCapability() {
        return gpsposCapability;
    }

    /**
     * Sets the value of the gpsposCapability property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGPSPOSCapability(String value) {
        this.gpsposCapability = value;
    }

    /**
     * Gets the value of the gpsposData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGPSPOSData() {
        return gpsposData;
    }

    /**
     * Sets the value of the gpsposData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGPSPOSData(String value) {
        this.gpsposData = value;
    }

    /**
     * Gets the value of the acquirerReferenceData031 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcquirerReferenceData031() {
        return acquirerReferenceData031;
    }

    /**
     * Sets the value of the acquirerReferenceData031 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcquirerReferenceData031(String value) {
        this.acquirerReferenceData031 = value;
    }

    /**
     * Gets the value of the responseSource property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseSource() {
        return responseSource;
    }

    /**
     * Sets the value of the responseSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseSource(String value) {
        this.responseSource = value;
    }

    /**
     * Gets the value of the responseSourceWhy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseSourceWhy() {
        return responseSourceWhy;
    }

    /**
     * Sets the value of the responseSourceWhy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseSourceWhy(String value) {
        this.responseSourceWhy = value;
    }

    /**
     * Gets the value of the messageSource property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageSource() {
        return messageSource;
    }

    /**
     * Sets the value of the messageSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageSource(String value) {
        this.messageSource = value;
    }

    /**
     * Gets the value of the messageWhy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageWhy() {
        return messageWhy;
    }

    /**
     * Sets the value of the messageWhy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageWhy(String value) {
        this.messageWhy = value;
    }

    /**
     * Gets the value of the traceidLifecycle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTraceidLifecycle() {
        return traceidLifecycle;
    }

    /**
     * Sets the value of the traceidLifecycle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTraceidLifecycle(String value) {
        this.traceidLifecycle = value;
    }

    /**
     * Gets the value of the balanceSequence property.
     * 
     */
    public int getBalanceSequence() {
        return balanceSequence;
    }

    /**
     * Sets the value of the balanceSequence property.
     * 
     */
    public void setBalanceSequence(int value) {
        this.balanceSequence = value;
    }

    /**
     * Gets the value of the balanceSequenceExthost property.
     * 
     */
    public int getBalanceSequenceExthost() {
        return balanceSequenceExthost;
    }

    /**
     * Sets the value of the balanceSequenceExthost property.
     * 
     */
    public void setBalanceSequenceExthost(int value) {
        this.balanceSequenceExthost = value;
    }

    /**
     * Gets the value of the paymentTokenId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentTokenId() {
        return paymentTokenId;
    }

    /**
     * Sets the value of the paymentTokenId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentTokenId(String value) {
        this.paymentTokenId = value;
    }

    /**
     * Gets the value of the paymentTokenCreator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentTokenCreator() {
        return paymentTokenCreator;
    }

    /**
     * Sets the value of the paymentTokenCreator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentTokenCreator(String value) {
        this.paymentTokenCreator = value;
    }

    /**
     * Gets the value of the paymentTokenExpdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentTokenExpdate() {
        return paymentTokenExpdate;
    }

    /**
     * Sets the value of the paymentTokenExpdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentTokenExpdate(String value) {
        this.paymentTokenExpdate = value;
    }

    /**
     * Gets the value of the paymentTokenType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentTokenType() {
        return paymentTokenType;
    }

    /**
     * Sets the value of the paymentTokenType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentTokenType(String value) {
        this.paymentTokenType = value;
    }

    /**
     * Gets the value of the paymentTokenStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentTokenStatus() {
        return paymentTokenStatus;
    }

    /**
     * Sets the value of the paymentTokenStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentTokenStatus(String value) {
        this.paymentTokenStatus = value;
    }

    /**
     * Gets the value of the paymentTokenCreatorStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentTokenCreatorStatus() {
        return paymentTokenCreatorStatus;
    }

    /**
     * Sets the value of the paymentTokenCreatorStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentTokenCreatorStatus(String value) {
        this.paymentTokenCreatorStatus = value;
    }

    /**
     * Gets the value of the paymentTokenWallet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentTokenWallet() {
        return paymentTokenWallet;
    }

    /**
     * Sets the value of the paymentTokenWallet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentTokenWallet(String value) {
        this.paymentTokenWallet = value;
    }

    /**
     * Gets the value of the paymentTokenDeviceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentTokenDeviceType() {
        return paymentTokenDeviceType;
    }

    /**
     * Sets the value of the paymentTokenDeviceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentTokenDeviceType(String value) {
        this.paymentTokenDeviceType = value;
    }

    /**
     * Gets the value of the paymentTokenLang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentTokenLang() {
        return paymentTokenLang;
    }

    /**
     * Sets the value of the paymentTokenLang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentTokenLang(String value) {
        this.paymentTokenLang = value;
    }

    /**
     * Gets the value of the paymentTokenDeviceTelNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentTokenDeviceTelNum() {
        return paymentTokenDeviceTelNum;
    }

    /**
     * Sets the value of the paymentTokenDeviceTelNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentTokenDeviceTelNum(String value) {
        this.paymentTokenDeviceTelNum = value;
    }

    /**
     * Gets the value of the paymentTokenDeviceIp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentTokenDeviceIp() {
        return paymentTokenDeviceIp;
    }

    /**
     * Sets the value of the paymentTokenDeviceIp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentTokenDeviceIp(String value) {
        this.paymentTokenDeviceIp = value;
    }

    /**
     * Gets the value of the paymentTokenDeviceId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentTokenDeviceId() {
        return paymentTokenDeviceId;
    }

    /**
     * Sets the value of the paymentTokenDeviceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentTokenDeviceId(String value) {
        this.paymentTokenDeviceId = value;
    }

    /**
     * Gets the value of the paymentTokenDeviceName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentTokenDeviceName() {
        return paymentTokenDeviceName;
    }

    /**
     * Sets the value of the paymentTokenDeviceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentTokenDeviceName(String value) {
        this.paymentTokenDeviceName = value;
    }

    /**
     * Gets the value of the paymentTokenActivationCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentTokenActivationCode() {
        return paymentTokenActivationCode;
    }

    /**
     * Sets the value of the paymentTokenActivationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentTokenActivationCode(String value) {
        this.paymentTokenActivationCode = value;
    }

    /**
     * Gets the value of the paymentTokenActivationExpiry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentTokenActivationExpiry() {
        return paymentTokenActivationExpiry;
    }

    /**
     * Sets the value of the paymentTokenActivationExpiry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentTokenActivationExpiry(String value) {
        this.paymentTokenActivationExpiry = value;
    }

    /**
     * Gets the value of the paymentTokenActivationMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentTokenActivationMethod() {
        return paymentTokenActivationMethod;
    }

    /**
     * Sets the value of the paymentTokenActivationMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentTokenActivationMethod(String value) {
        this.paymentTokenActivationMethod = value;
    }

    /**
     * Gets the value of the paymentTokenActivationMethodData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentTokenActivationMethodData() {
        return paymentTokenActivationMethodData;
    }

    /**
     * Sets the value of the paymentTokenActivationMethodData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentTokenActivationMethodData(String value) {
        this.paymentTokenActivationMethodData = value;
    }

    /**
     * Gets the value of the iccSystemRelatedDataDE55 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getICCSystemRelatedDataDE55() {
        return iccSystemRelatedDataDE55;
    }

    /**
     * Sets the value of the iccSystemRelatedDataDE55 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setICCSystemRelatedDataDE55(String value) {
        this.iccSystemRelatedDataDE55 = value;
    }

    /**
     * Gets the value of the merchName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchName() {
        return merchName;
    }

    /**
     * Sets the value of the merchName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchName(String value) {
        this.merchName = value;
    }

    /**
     * Gets the value of the merchStreet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchStreet() {
        return merchStreet;
    }

    /**
     * Sets the value of the merchStreet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchStreet(String value) {
        this.merchStreet = value;
    }

    /**
     * Gets the value of the merchCity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchCity() {
        return merchCity;
    }

    /**
     * Sets the value of the merchCity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchCity(String value) {
        this.merchCity = value;
    }

    /**
     * Gets the value of the merchRegion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchRegion() {
        return merchRegion;
    }

    /**
     * Sets the value of the merchRegion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchRegion(String value) {
        this.merchRegion = value;
    }

    /**
     * Gets the value of the merchPostcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchPostcode() {
        return merchPostcode;
    }

    /**
     * Sets the value of the merchPostcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchPostcode(String value) {
        this.merchPostcode = value;
    }

    /**
     * Gets the value of the merchCountry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchCountry() {
        return merchCountry;
    }

    /**
     * Sets the value of the merchCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchCountry(String value) {
        this.merchCountry = value;
    }

    /**
     * Gets the value of the merchTel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchTel() {
        return merchTel;
    }

    /**
     * Sets the value of the merchTel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchTel(String value) {
        this.merchTel = value;
    }

    /**
     * Gets the value of the merchURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchURL() {
        return merchURL;
    }

    /**
     * Sets the value of the merchURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchURL(String value) {
        this.merchURL = value;
    }

    /**
     * Gets the value of the merchNameOther property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchNameOther() {
        return merchNameOther;
    }

    /**
     * Sets the value of the merchNameOther property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchNameOther(String value) {
        this.merchNameOther = value;
    }

    /**
     * Gets the value of the merchNetId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchNetId() {
        return merchNetId;
    }

    /**
     * Sets the value of the merchNetId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchNetId(String value) {
        this.merchNetId = value;
    }

    /**
     * Gets the value of the merchTaxId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchTaxId() {
        return merchTaxId;
    }

    /**
     * Sets the value of the merchTaxId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchTaxId(String value) {
        this.merchTaxId = value;
    }

    /**
     * Gets the value of the merchContact property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchContact() {
        return merchContact;
    }

    /**
     * Sets the value of the merchContact property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchContact(String value) {
        this.merchContact = value;
    }

}
