//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.20 at 04:14:25 PM EEST 
//


package ehi.web.service.client.soap.schemas.gps;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ResponseMsg complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ResponseMsg"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="Responsestatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CurBalance" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="AvlBalance" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="Acknowledgement" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="LoadAmount" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="Bill_Amt_Approved" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="Update_Balance" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="New_Balance_Sequence_Exthost" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="CVV2_Result" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResponseMsg", propOrder = {

})
public class ResponseMsg {

    @XmlElement(name = "Responsestatus")
    protected String responsestatus;
    @XmlElement(name = "CurBalance")
    protected Double curBalance;
    @XmlElement(name = "AvlBalance")
    protected Double avlBalance;
    @XmlElement(name = "Acknowledgement", required = true)
    protected String acknowledgement;
    @XmlElement(name = "LoadAmount")
    protected Double loadAmount;
    @XmlElement(name = "Bill_Amt_Approved")
    protected Double billAmtApproved;
    @XmlElement(name = "Update_Balance")
    protected Integer updateBalance;
    @XmlElement(name = "New_Balance_Sequence_Exthost")
    protected Integer newBalanceSequenceExthost;
    @XmlElement(name = "CVV2_Result")
    protected String cvv2Result;

    /**
     * Gets the value of the responsestatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponsestatus() {
        return responsestatus;
    }

    /**
     * Sets the value of the responsestatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponsestatus(String value) {
        this.responsestatus = value;
    }

    /**
     * Gets the value of the curBalance property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getCurBalance() {
        return curBalance;
    }

    /**
     * Sets the value of the curBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setCurBalance(Double value) {
        this.curBalance = value;
    }

    /**
     * Gets the value of the avlBalance property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getAvlBalance() {
        return avlBalance;
    }

    /**
     * Sets the value of the avlBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setAvlBalance(Double value) {
        this.avlBalance = value;
    }

    /**
     * Gets the value of the acknowledgement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcknowledgement() {
        return acknowledgement;
    }

    /**
     * Sets the value of the acknowledgement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcknowledgement(String value) {
        this.acknowledgement = value;
    }

    /**
     * Gets the value of the loadAmount property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getLoadAmount() {
        return loadAmount;
    }

    /**
     * Sets the value of the loadAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setLoadAmount(Double value) {
        this.loadAmount = value;
    }

    /**
     * Gets the value of the billAmtApproved property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getBillAmtApproved() {
        return billAmtApproved;
    }

    /**
     * Sets the value of the billAmtApproved property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setBillAmtApproved(Double value) {
        this.billAmtApproved = value;
    }

    /**
     * Gets the value of the updateBalance property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getUpdateBalance() {
        return updateBalance;
    }

    /**
     * Sets the value of the updateBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setUpdateBalance(Integer value) {
        this.updateBalance = value;
    }

    /**
     * Gets the value of the newBalanceSequenceExthost property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNewBalanceSequenceExthost() {
        return newBalanceSequenceExthost;
    }

    /**
     * Sets the value of the newBalanceSequenceExthost property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNewBalanceSequenceExthost(Integer value) {
        this.newBalanceSequenceExthost = value;
    }

    /**
     * Gets the value of the cvv2Result property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCVV2Result() {
        return cvv2Result;
    }

    /**
     * Sets the value of the cvv2Result property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCVV2Result(String value) {
        this.cvv2Result = value;
    }

}
